### ISSUE TITLE
Create cool elementary icon

### ISSUE THREAD

**Issue by bartzaalberg** [bartzaalberg/lottery#1]
The app has a very ugly icon. Can anyone please create a new one?

**Comment by kosijer** [comment]
I'm taking this one. Cheers

**Comment by bartzaalberg** [comment]
Thank you @kosijer for the awesome icon!

**Comment by kosijer** [comment]
Thanks. Can I actually post replaced icons to the branch please? I'm collecting accepted PRs and would really appreciate if you can take my changes. I can do that this evening. Thank you.

**Comment by bartzaalberg** [comment]
Hahahaha sure

Op 25 okt. 2017 18:16 schreef Nebojsa Kosijer <notifications@github.com>:

Thanks. Can I actually post replaced icons to the branch please? I'm collecting accepted PRs and would really appreciate if you can take my changes. I can do that this evening. Thank you.

**Comment by kosijer** [comment]
Great :)

**Comment by kosijer** [comment]
...and this one should be opened as well, please :)

(all done already, just need to push changes)
