### ISSUE TITLE
Add appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/lottery#11]
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by bartzaalberg** [comment]
It's been released.

**Comment by bartzaalberg** [comment]
Not working correctly. Lines are translated but some lines are missing, will have to look at it again.

**Comment by NathanBnm** [comment]
Okay, just notify me when it's ready.

**Comment by bartzaalberg** [comment]
It's ready. Translations already worked. I just forgot to actually translate to Dutch :) Closing this. Please add French if you have some spare time.
