### ISSUE TITLE
Add some sort of batch import of names

### ISSUE THREAD

**Issue by DanyGee** [bartzaalberg/lottery#5]
It may come handy to have an ability to import multiple names at once, lets say from a *txt/*csv file.
Imagine you are a youtuber and you want to pick a winner from thousands of names.

**Comment by bartzaalberg** [comment]
Do you maybe have a format for me that i can work use for this? Because i don't know what defaults  i should use

**Comment by DanyGee** [comment]
Dive into this:
CSV
https://en.wikipedia.org/wiki/Comma-separated_values 

As for text, maybe something like line, by line. Every line in txt file will be a new participant.
Simple as that.

**Comment by bartzaalberg** [comment]
Added ability to import CSV
